export const translations = {
    ja: {
        title: "TaikoNauts 変換ツール",
        subtitle: "Final Edition - HitCount対応版",
        dropzone: "ここにフォルダをドラッグ＆ドロップ",
        status_idle: "準備完了...",
        step_upload: "アップロード",
        step_basic: "基本設定",
        step_images: "画像設定",
        step_songs: "曲設定",
        step_export: "出力方法",
        step1_desc: "TJA ファイルと音源を含むフォルダをアップロードしてください",
        rank_label: "段位ランクを選択",
        rank_note: "フォルダ番号(1-19)とDanIndex(0-18)を決定します。",
        dan_title_label: "段位タイトル (フォルダ名)",
        dan_title_note: "フォルダ名とJSONのタイトルになります。",
        image_settings_label: "画像設定 (各種Plate・Panel)",
        image_settings_note: "JSON の各パスに設定し、選択したファイルを ZIP に同梱します。",
        plate_label: "段位プレート (danPlatePath)",
        panel_side_label: "サイドパネル (danPanelSidePath)",
        title_plate_label: "タイトルプレート (danTitlePlatePath)",
        mini_plate_label: "ミニプレート (danMiniPlatePath)",
        hidden_song_label: "隠し曲設定 (タイトルを ??? にする)",
        export_mode_label: "出力方法",
        export_zip: "ZIP ダウンロード",
        export_preview: "プレビューとコピー",
        export_info: "すべての設定が完了しました。下の「変換開始」ボタンをクリックして処理を開始してください。",
        run_btn: "変換開始",
        run_btn_processing: "処理中...",
        run_btn_done: "完了！",
        run_btn_error: "エラー",
        btn_prev: "← 前へ",
        btn_next: "次へ →",
        preview_title: "変換結果プレビュー",
        preview_copy: "内容をコピー",
        preview_close: "閉じる",
        copy_success: "クリップボードにコピーしました",
        log_tja_found: "TJAファイルを検出: ",
        log_multiple_tja: "注意: 複数のTJAがあります。優先します: ",
        log_no_tja: "エラー: フォルダ内にTJAファイルが見つかりません。",
        log_scan_done: "曲を検出。詳細を設定してください。",
        log_no_nextsong: "曲分割タグ未検出。",
        log_start_conversion: "設定: ",
        log_done: "全処理完了。",
        log_images_found: " 枚の画像を検出。",
        img_none: "(指定しない / デフォルト: ",
        theme_light: "ライトモード",
            theme_dark: "ダークモード",
            log_convert_start: "変換開始...",
            log_processing: "変換処理中...",
            log_convert_done: "変換完了、ファイル出力",
            log_generating_zip: "ZIP ファイル生成中...",
            log_file_added: "追加済み: ",
            log_file_added_binary: "追加済み: ",
            log_compressing_zip: "ZIP 圧縮中...",
            log_showing_preview: "プレビュー表示中...",
            log_failed: "失敗: "
    },
    en: {
        title: "TaikoNauts Conversion Tool",
        subtitle: "Final Edition - HitCount Supported",
        dropzone: "Drag & Drop folder here",
        status_idle: "Ready...",
        step_upload: "Upload",
        step_basic: "Basic Settings",
        step_images: "Image Settings",
        step_songs: "Song Settings",
        step_export: "Export Method",
        step1_desc: "Upload a folder containing TJA files and audio files",
        rank_label: "Select Rank",
        rank_note: "Determines folder number (1-19) and DanIndex (0-18).",
        dan_title_label: "Dan Title (Folder Name)",
        dan_title_note: "Used as folder name and JSON title.",
        image_settings_label: "Image Settings (Plates/Panels)",
        image_settings_note: "Settings for JSON paths; files will be included in ZIP.",
        plate_label: "Dan Plate (danPlatePath)",
        panel_side_label: "Side Panel (danPanelSidePath)",
        title_plate_label: "Title Plate (danTitlePlatePath)",
        mini_plate_label: "Mini Plate (danMiniPlatePath)",
        hidden_song_label: "Hidden Song Settings (Set title to ???)",
        export_mode_label: "Export Mode",
        export_zip: "ZIP Download",
        export_preview: "Preview & Copy",
        export_info: "All settings completed. Click the \"Start Conversion\" button below to begin processing.",
        run_btn: "Start Conversion",
        run_btn_processing: "Processing...",
        run_btn_done: "Done!",
        run_btn_error: "Error",
        btn_prev: "← Previous",
        btn_next: "Next →",
        preview_title: "Conversion Preview",
        preview_copy: "Copy Content",
        preview_close: "Close",
        copy_success: "Copied to clipboard",
        log_tja_found: "TJA file detected: ",
        log_multiple_tja: "Warning: Multiple TJAs found. Prioritizing: ",
        log_no_tja: "Error: No TJA file found in the folder.",
        log_scan_done: "songs detected. Please configure details.",
        log_no_nextsong: "No #NEXTSONG tag detected.",
        log_start_conversion: "Settings: ",
        log_done: "All processes completed.",
        log_images_found: " images found.",
        img_none: "(None / Default: ",
        theme_light: "Light Mode",
            theme_dark: "Dark Mode",
            log_convert_start: "Conversion starting...",
            log_processing: "Processing conversion...",
            log_convert_done: "Conversion complete, output",
            log_generating_zip: "Generating ZIP file...",
            log_file_added: "Added: ",
            log_file_added_binary: "Added: ",
            log_compressing_zip: "Compressing ZIP...",
            log_showing_preview: "Showing preview...",
            log_failed: "Failed: "
    },
    "zh-TW": {
        title: "TaikoNauts 轉換工具",
        subtitle: "Final Edition - 支援 HitCount",
        dropzone: "將資料夾拖放到此處",
        status_idle: "準備就緒...",
        step_upload: "上傳",
        step_basic: "基本設定",
        step_images: "圖片設定",
        step_songs: "曲目設定",
        step_export: "匯出方式",
        step1_desc: "上傳包含 TJA 檔案和音樂的資料夾",
        rank_label: "選擇段位階級",
        rank_note: "決定資料夾編號 (1-19) 與 DanIndex (0-18)。",
        dan_title_label: "段位標題 (資料夾名稱)",
        dan_title_note: "這將作為資料夾名稱與 JSON 內的標題。",
        image_settings_label: "圖片設定 (各類 Plate/Panel)",
        image_settings_note: "設定 JSON 路徑，選擇的檔案將包含在 ZIP 中。",
        plate_label: "段位合格牌 (danPlatePath)",
        panel_side_label: "側邊欄 (danPanelSidePath)",
        title_plate_label: "標題牌 (danTitlePlatePath)",
        mini_plate_label: "迷你合格牌 (danMiniPlatePath)",
        hidden_song_label: "隱藏曲設定 (將標題改為 ???)",
        export_mode_label: "匯出方式",
        export_zip: "ZIP 下載",
        export_preview: "預覽與複製",
        export_info: "所有設定已完成。點擊下方「開始轉換」按鈕開始處理。",
        run_btn: "開始轉換",
        run_btn_processing: "處理中...",
        run_btn_done: "完成！",
        run_btn_error: "錯誤",
        btn_prev: "← 上一步",
        btn_next: "下一步 →",
        preview_title: "轉換結果預覽",
        preview_copy: "複製內容",
        preview_close: "關閉",
        copy_success: "已複製到剪貼簿",
        log_tja_found: "偵測到 TJA 檔案: ",
        log_multiple_tja: "注意: 偵測到多個 TJA。將優先使用: ",
        log_no_tja: "錯誤: 資料夾內找不到 TJA 檔案。",
        log_scan_done: "首歌曲。請設定詳細資訊。",
        log_no_nextsong: "未偵測到曲目分割標籤 (#NEXTSONG)。",
        log_start_conversion: "設定: ",
        log_done: "所有處理已完成。",
        log_images_found: " 張圖片已偵測。",
        img_none: "(不指定 / 預設: ",
        theme_light: "淺色模式",
            theme_dark: "深色模式",
            log_convert_start: "轉換開始...",
            log_processing: "轉換處理中...",
            log_convert_done: "轉換完成，輸出",
            log_generating_zip: "正在生成 ZIP 檔案...",
            log_file_added: "已添加: ",
            log_file_added_binary: "已添加: ",
            log_compressing_zip: "正在壓縮 ZIP...",
            log_showing_preview: "正在顯示預覽...",
            log_failed: "失敗: "
    }
};
